version: '3.8'

name: stride

services:
  identity-ms:
    image: nlnm/stride-identity-ms:latest
    container_name: identity-ms
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8081"
    restart: on-failure
    volumes:
      - ./stride-config/identity:/app/resources
    environment:
      SPRING_CONFIG_LOCATION: file:/app/resources/
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-Dlogging.config=file:/app/resources/logback-spring.xml"
    networks:
      - stride-network
  bridge-ms:
    image: nlnm/stride-bridge-ms:latest
    container_name: bridge-ms
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8082"
    restart: on-failure
    volumes:
      - ./stride-config/bridge:/app/resources
    environment:
      SPRING_CONFIG_LOCATION: file:/app/resources/
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-Dlogging.config=file:/app/resources/logback-spring.xml"
    networks:
      - stride-network
  profile-ms:
    image: nlnm/stride-profile-ms:latest
    container_name: profile-ms
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8083"
    restart: on-failure
    volumes:
      - ./stride-config/profile:/app/resources
    environment:
      SPRING_CONFIG_LOCATION: file:/app/resources/
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-Dlogging.config=file:/app/resources/logback-spring.xml"
    networks:
      - stride-network
  core-ms:
    image: nlnm/stride-core-ms:latest
    container_name: core-ms
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8084"
    restart: on-failure
    volumes:
      - ./stride-config/core:/app/resources
    environment:
      SPRING_CONFIG_LOCATION: file:/app/resources/
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-Dlogging.config=file:/app/resources/logback-spring.xml"
    networks:
      - stride-network
  metric-ms:
    image: nlnm/stride-metric-ms:latest
    container_name: metric-ms
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8085"
    restart: on-failure
    volumes:
      - ./stride-config/metric:/app/resources
    environment:
      SPRING_CONFIG_LOCATION: file:/app/resources/
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-Dlogging.config=file:/app/resources/logback-spring.xml"
    networks:
      - stride-network
  gateway:
    image: nlnm/stride-gateway:latest
    container_name: gateway-ms
    depends_on:
      - identity-ms
      - bridge-ms
      - profile-ms
      - core-ms
      - metric-ms
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - ./stride-config/gateway:/app/resources
    environment:
      SPRING_CONFIG_LOCATION: file:/app/resources/
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - stride-network
  kafka:
    image: bitnami/kafka:3.8.0
    container_name: kafka
    hostname: kafka
    restart: always
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_MESSAGE_MAX_BYTES=2000000
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=2000000
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - stride-network
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 30s
      timeout: 10s
      retries: 3
  grafana-agent:
    image: grafana/agent:v0.44.2
    container_name: grafana-agent
    restart: unless-stopped
    volumes:
      - ./stride-config/grafana-agent/grafana-agent.yml:/etc/agent.yaml:ro
    command:
      - '--config.file=/etc/agent.yaml'
    networks:
      - stride-network

networks:
  stride-network:
    driver: bridge
