version: '3.8'

name: stride-log

services:
  loki:
    image: grafana/loki:3.5
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    networks:
      - stride-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - stride-network

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    restart: unless-stopped
    ports:
      - "3200:3200"
      - "4317"
    command: [ "-config.file=/etc/tempo-config.yml" ]
    volumes:
      - ./z-etc/log/tempo-config.yml:/etc/tempo-config.yml
    networks:
      - stride-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.82.0
    container_name: otel-collector
    restart: always
    command: ["--config=/etc/otelcol-contrib/otel-collector.yml"]
    volumes:
      - ./z-etc/log/otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - loki
      - tempo
      - prometheus
    networks:
      - stride-network

  grafana:
    image: grafana/grafana:12.0.1
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - loki
      - tempo
      - prometheus
    volumes:
      - ./z-etc/log/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - "3000:3000"
    networks:
      - stride-network

networks:
  stride-network:
    driver: bridge