name: Deploy to VPS

on:
  push:
    branches: [ feature/auto-deploy-to-vps ]

jobs:
  build-gateway:
    uses: ./.github/workflows/api-gateway-build.yml
    secrets: inherit

  build-bridge-ms:
    uses: ./.github/workflows/bridge-service-build.yml
    secrets: inherit

  build-core-ms:
    uses: ./.github/workflows/core-service-build.yml
    secrets: inherit

  build-identity-ms:
    uses: ./.github/workflows/identity-service-build.yml
    secrets: inherit

  build-profile-ms:
    uses: ./.github/workflows/profile-service-build.yml
    secrets: inherit

  build-route-ms:
    uses: ./.github/workflows/route-service-build.yml
    secrets: inherit

  deploy-to-vps:
    needs: [
      build-gateway,
      build-bridge-ms,
      build-core-ms,
      build-identity-ms,
      build-profile-ms,
      build-route-ms
    ]
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e
          
            cd stride

            echo "Stopping and removing containers..."
            docker-compose down --volumes --remove-orphans

            echo "Removing all unused images, containers, volumes, and networks..."
            docker system prune -af --volumes

            echo "Pulling fresh images..."
            docker-compose pull

            echo "Starting containers..."
            docker-compose up -d
          EOF

  ping-bridge-service:
    needs: [
      deploy-to-vps
    ]
    runs-on: ubuntu-latest
    steps:
      - name: Ping bridge-service
        run: |
          echo "Pinging bridge-service..."
          VPS_HOST=${{ secrets.VPS_HOST }}
          VPS_PORT=${{ secrets.VPS_PORT }}
          URL="http://${VPS_HOST}:8080/api/v1/bridge/ping"
          
          while true; do
            curl -s "$URL" || echo "bridge-ms is not responding"
            sleep 5
          done

  ping-core-service:
    needs: [
      deploy-to-vps
    ]
    runs-on: ubuntu-latest
    steps:
      - name: Ping core-service
        run: |
          echo "Pinging core-service..."
          VPS_HOST=${{ secrets.VPS_HOST }}
          URL="http://${VPS_HOST}:8080/api/v1/core/ping"
          
          while true; do
            curl -s "$URL" || echo "core-ms is not responding"
            sleep 5
          done

  ping-identity-service:
    needs: [
      deploy-to-vps
    ]
    runs-on: ubuntu-latest
    steps:
      - name: Ping identity-service
        run: |
          echo "Pinging identity-service..."
          VPS_HOST=${{ secrets.VPS_HOST }}
          URL="http://${VPS_HOST}:8080/api/v1/identity/ping"
          
          while true; do
            curl -s "$URL" || echo "identity-ms is not responding"
            sleep 5
          done

  ping-profile-service:
    needs: [
      deploy-to-vps
    ]
    runs-on: ubuntu-latest
    steps:
      - name: Ping profile-service
        run: |
          echo "Pinging profile-service..."
          VPS_HOST=${{ secrets.VPS_HOST }}
          URL="http://${VPS_HOST}:8080/api/v1/profile/ping"
          
          while true; do
            curl -s "$URL" || echo "profile-ms is not responding"
            sleep 5
          done

  ping-route-service:
    needs: [
      deploy-to-vps
    ]
    runs-on: ubuntu-latest
    steps:
      - name: Ping route-service
        run: |
          echo "Pinging route-service..."
          VPS_HOST=${{ secrets.VPS_HOST }}
          URL="http://${VPS_HOST}:8080/api/v1/route/ping"

          while true; do
            curl -s "$URL" || echo "route-ms is not responding"
            sleep 5
          done
      
