name: Deploy to VPS

on:
  push:
    branches: [ feature/auto-deploy-to-vps ]

jobs:
  build-gateway:
    uses: ./.github/workflows/api-gateway-build.yml
    secrets: inherit

  build-bridge-ms:
    uses: ./.github/workflows/bridge-service-build.yml
    secrets: inherit

  build-core-ms:
    uses: ./.github/workflows/core-service-build.yml
    secrets: inherit

  build-identity-ms:
    uses: ./.github/workflows/identity-service-build.yml
    secrets: inherit

  build-profile-ms:
    uses: ./.github/workflows/profile-service-build.yml
    secrets: inherit

  build-route-ms:
    uses: ./.github/workflows/route-service-build.yml
    secrets: inherit

  deploy-to-vps:
    needs: [
      build-gateway,
      build-bridge-ms,
      build-core-ms,
      build-identity-ms,
      build-profile-ms,
      build-route-ms
    ]
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa <<< "${{ secrets.VPS_PASSPHRASE }}"

          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e

            echo "Stopping and removing containers..."
            docker-compose down --volumes --remove-orphans

            echo "Removing all unused images, containers, volumes, and networks..."
            docker system prune -af --volumes

            echo "Pulling fresh images..."
            docker-compose pull

            echo "Starting containers..."
            docker-compose up -d
          EOF
      
